name: Web Utils Realase & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # body_path: ./changelog.md
          draft: false
          prerelease: false

  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: release
    # if: github.repository_owner == 'inperceptic'
    steps:
      - name: Checkout Publish
        uses: actions/checkout@v3
      # - name: Setup .npmrc
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.x
      #     registry-url: 'https://registry.npmjs.org'

      # - name: Install dependencies
      #   run: |
      #     echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
      #     npm ci
      #- run: echo "registry=https://npm.pkg.github.com/@InPerceptic" >> .npmrc
      #- run: npm run addscope
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@InPerceptic'
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com:_authToken=${{ secrets.PAT }}" >
          ~/.npmrc

      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_ACCESS_TOKEN }}
