name: publish Web Utils package to GitHub
run-name: publish Web Utils package to GitHub
# [push, fork]
on:
  # label:
  # types:
  #   - created
  #   push:
  #     branches:
  #       - main
  #       - 'releases/**'
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Release
  #       uses: actions/checkout@v3
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: ${{ github.ref }}
  #         # body_path: ./changelog.md
  #         draft: false
  #         prerelease: false
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     # Setup .npmrc file to publish to npm
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'
  #         scope: '@inperceptic'
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    # needs: [release]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@inperceptic'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
